use crate::{benchmarks::AllResults, manifest::RunManifest};
use std::path::Path;

pub fn write_zenodo_dir(out_dir: &Path, _results: &AllResults, mf: &RunManifest) {
    let zenodo_dir = out_dir.join("zenodo");
    std::fs::create_dir_all(&zenodo_dir).expect("create zenodo dir");
    let data_dir = zenodo_dir.join("data");
    std::fs::create_dir_all(&data_dir).expect("create zenodo/data dir");

    // Copy benchmark JSONs
    for entry in &mf.artifacts {
        if entry.name.ends_with(".json") && !entry.name.starts_with("manifest") {
            let src = out_dir.join(&entry.name);
            let dst = data_dir.join(&entry.name);
            let _ = std::fs::copy(src, dst);
        }
    }

    // metadata.json
    let metadata = serde_json::json!({
        "upload_type": "dataset",
        "title": format!("PSE Benchmark Suite v{} — Pfauenthron++, ETV, Constitutional, Anomaly, Agent", env!("CARGO_PKG_VERSION")),
        "creators": [{"name": "Klemm, Sebastian", "affiliation": ""}],
        "description": "Reproducible benchmark suite for Kosmocrates. \
    Covers retrieval quality (Pfauenthron++ D=ψ·ρ·ω vs BM25 vs cosine-only), \
    noise robustness, constitutional governance precision/recall, \
    Epistemic Thunderbolt Vector reasoning chain coherence, anomaly detection F1, \
    agent relevance ranking, and retrieval scalability. \
    All benchmarks run with a single cargo command. No external API calls required.",
        "access_right": "open",
        "license": "MIT",
        "keywords": ["post-symbolic", "retrieval", "constitutional AI", "anomaly detection", "Rust", "epistemic AI"],
        "version": env!("CARGO_PKG_VERSION"),
        "language": "eng",
        "related_identifiers": [
            {"relation": "isSupplementTo", "identifier": "https://github.com/lashsesh/pse", "scheme": "url"}
        ],
        "notes": "Generated by: cargo run --release -p pse-paper-bench",
        "pse_manifest_hash": mf.self_hash,
        "run_timestamp": mf.timestamp,
    });
    let meta_str = serde_json::to_string_pretty(&metadata).expect("serialize metadata");
    std::fs::write(zenodo_dir.join("metadata.json"), &meta_str).expect("write metadata.json");

    // README.md
    let readme = format!(
        "# PSE Benchmark Suite v{}\n\n\
## How to reproduce\n\n\
```bash\ngit clone https://github.com/lashsesh/pse\ncd pse\n\
cargo run --release -p pse-paper-bench -- --out ./bench-output\n```\n\n\
## File listing\n\n\
{}\n\n\
## Manifest hash\n\n`{}`\n",
        env!("CARGO_PKG_VERSION"),
        mf.artifacts
            .iter()
            .map(|a| format!("- `{}` (SHA-256: `{}`)", a.name, a.sha256))
            .collect::<Vec<_>>()
            .join("\n"),
        mf.self_hash
    );
    std::fs::write(zenodo_dir.join("README.md"), &readme).expect("write zenodo README.md");
}
