//! Chunks an LLM text response into PSE observations.
//!
//! Each chunk becomes one `Vec<u8>` observation — a sentence or short
//! paragraph unit. A sliding window over these chunks forms each tick's
//! batch, so the PSE graph evolves with the semantic flow of the response.
//!
//! ## Multi-vertex topology (Option B)
//!
//! Each chunk is assigned a content-addressed source ID derived from
//! FNV-1a hash of its bytes.  This means:
//!   - Every *unique* chunk becomes its own vertex in the PSE graph.
//!   - A window of 4 chunks creates 4 distinct vertices with 6 pairwise
//!     edges — a real co-occurrence topology, not a single self-loop.
//!   - Identical chunks in later sessions map to the *same* vertex,
//!     so cross-session replay still hits pattern memory.
//!
//! ## Semantic phase — three-tier strategy
//!
//! Phase hint assigned to each chunk determines how the PSE carrier
//! differentiates semantic regions.  Three tiers, best-to-fallback:
//!
//! **Tier 1 — local embedding file** (`PSE_LLM_EMBEDDING_FILE` is set)
//!   A TSV file generated by `scripts/gen_word_phases.py` from GloVe /
//!   FastText vectors.  For each chunk, the 2D unit-projected embedding
//!   vectors of its words are averaged and `atan2(sum_y, sum_x)` gives the
//!   phase.  This is a genuine semantic signal: words with similar meaning
//!   land in the same angular region of the embedding space.
//!
//! **Tier 2 — character 4-gram circular mean** (no file set)
//!   FNV-1a hashes of overlapping character 4-grams, mapped to [0, 2π)
//!   and averaged as unit vectors (circular mean).  Captures morphological
//!   families ("therm*", "entr*", "activ*") better than whole-word hashes
//!   because short substrings are shared across word forms.
//!
//! **Tier 3 — byte-average fallback** (< 4 characters)
//!   Only reached for very short fragments.

use std::collections::HashMap;
use std::f64::consts::TAU;
use std::sync::OnceLock;

use pse_graph::{ObservationAdapter, ObserveError};
use pse_types::{content_address_raw, MeasurementContext, Observation, ProvenanceEnvelope};

// ── Helpers ───────────────────────────────────────────────────────────────────

fn fnv1a_u64(data: &[u8]) -> u64 {
    let mut h: u64 = 0xcbf29ce484222325;
    for &b in data {
        h ^= b as u64;
        h = h.wrapping_mul(0x100000001b3);
    }
    h
}

// ── Tier 3: byte-average fallback ────────────────────────────────────────────

fn byte_avg_phase(raw: &[u8]) -> f64 {
    if raw.is_empty() {
        return 0.0;
    }
    let avg: f64 = raw.iter().map(|&b| b as f64).sum::<f64>() / raw.len() as f64;
    (avg / 255.0) * TAU
}

// ── Tier 2: character 4-gram circular mean ────────────────────────────────────

fn char_4gram_phase(raw: &[u8]) -> f64 {
    let text = std::str::from_utf8(raw).unwrap_or("").to_lowercase();
    let chars: Vec<char> = text.chars().collect();
    if chars.len() < 4 {
        return byte_avg_phase(raw);
    }
    let mut sum_sin = 0.0_f64;
    let mut sum_cos = 0.0_f64;
    let mut count = 0usize;
    for w in chars.windows(4) {
        let s: String = w.iter().collect();
        let hash = fnv1a_u64(s.as_bytes());
        let phi = (hash as f64 / u64::MAX as f64) * TAU;
        sum_sin += phi.sin();
        sum_cos += phi.cos();
        count += 1;
    }
    if count == 0 {
        0.0
    } else {
        sum_sin.atan2(sum_cos).rem_euclid(TAU)
    }
}

// ── Tier 1: local embedding file ─────────────────────────────────────────────

/// Word → unit-circle (x, y) loaded from a PSE word-phase file.
/// Generated by `scripts/gen_word_phases.py` from GloVe / FastText vectors.
pub struct WordEmbeddings {
    map: HashMap<String, (f32, f32)>,
}

impl WordEmbeddings {
    /// Load from a tab-separated file: `word\tx\ty\n`
    /// Lines starting with `#` are treated as comments and skipped.
    pub fn load(path: &str) -> Result<Self, String> {
        let content = std::fs::read_to_string(path)
            .map_err(|e| format!("PSE_LLM_EMBEDDING_FILE {path}: {e}"))?;
        let mut map = HashMap::new();
        for line in content.lines() {
            let line = line.trim();
            if line.is_empty() || line.starts_with('#') {
                continue;
            }
            let mut parts = line.splitn(3, '\t');
            let word = match parts.next() {
                Some(w) => w,
                None => continue,
            };
            let x_str = match parts.next() {
                Some(s) => s,
                None => continue,
            };
            let y_str = match parts.next() {
                Some(s) => s,
                None => continue,
            };
            let x: f32 = match x_str.parse() {
                Ok(v) => v,
                Err(_) => continue,
            };
            let y: f32 = match y_str.parse() {
                Ok(v) => v,
                Err(_) => continue,
            };
            map.insert(word.to_string(), (x, y));
        }
        if map.is_empty() {
            return Err(format!(
                "PSE_LLM_EMBEDDING_FILE {path}: no valid entries found"
            ));
        }
        Ok(Self { map })
    }

    pub fn len(&self) -> usize {
        self.map.len()
    }

    fn lookup(&self, word: &str) -> Option<(f32, f32)> {
        self.map.get(word).copied()
    }
}

static WORD_EMBEDDINGS: OnceLock<Option<WordEmbeddings>> = OnceLock::new();

fn get_embeddings() -> Option<&'static WordEmbeddings> {
    WORD_EMBEDDINGS
        .get_or_init(|| match std::env::var("PSE_LLM_EMBEDDING_FILE") {
            Ok(path) => match WordEmbeddings::load(&path) {
                Ok(emb) => {
                    eprintln!(
                        "[PSE] Embedding phase: loaded {} words from {:?}",
                        emb.len(),
                        path
                    );
                    Some(emb)
                }
                Err(e) => {
                    eprintln!("[PSE] Warning: {e} — falling back to char-4gram phase");
                    None
                }
            },
            Err(_) => None,
        })
        .as_ref()
}

/// Phase from 2D embedding projection: circular mean of per-word unit vectors.
/// Falls back to char_4gram_phase for words not in the vocabulary.
fn embedding_phase(raw: &[u8], emb: &WordEmbeddings) -> f64 {
    let text = std::str::from_utf8(raw).unwrap_or("").to_lowercase();
    let mut sum_x = 0.0_f64;
    let mut sum_y = 0.0_f64;
    let mut count = 0usize;
    for word in text.split(|c: char| !c.is_alphabetic()) {
        if word.len() < 2 {
            continue;
        }
        if let Some((x, y)) = emb.lookup(word) {
            sum_x += x as f64;
            sum_y += y as f64;
            count += 1;
        }
    }
    if count == 0 {
        // No known words in chunk — fall through to char 4-gram
        char_4gram_phase(raw)
    } else {
        sum_y.atan2(sum_x).rem_euclid(TAU)
    }
}

/// Compute phase for a raw chunk using the best available tier.
fn semantic_phase(raw: &[u8]) -> f64 {
    if let Some(emb) = get_embeddings() {
        embedding_phase(raw, emb)
    } else {
        char_4gram_phase(raw)
    }
}

/// Public: phase value for a raw chunk (used for semantic windowing / diagnostics).
pub fn chunk_phase(raw: &[u8]) -> f64 {
    semantic_phase(raw)
}

/// Return the name of the active phase tier (for startup diagnostics).
pub fn phase_tier_name() -> &'static str {
    if get_embeddings().is_some() {
        "embedding (Tier 1)"
    } else {
        "char-4gram (Tier 2)"
    }
}

/// Count how many chunks have ≥1 word covered by the embedding vocabulary.
/// Returns `None` when no embedding file is loaded (Tier 2/3 active).
pub fn embedding_stats(chunks: &[Vec<u8>]) -> Option<(usize, usize)> {
    let emb = get_embeddings()?;
    let hits = chunks
        .iter()
        .filter(|raw| {
            std::str::from_utf8(raw)
                .unwrap_or("")
                .to_lowercase()
                .split(|c: char| !c.is_alphabetic())
                .filter(|w| w.len() >= 2)
                .any(|w| emb.lookup(w).is_some())
        })
        .count();
    Some((hits, chunks.len()))
}

// ── TextPhaseAdapter ──────────────────────────────────────────────────────────

pub struct TextPhaseAdapter {
    source_id: String,
}

impl TextPhaseAdapter {
    pub fn new(source: impl Into<String>) -> Self {
        Self {
            source_id: source.into(),
        }
    }
}

impl ObservationAdapter for TextPhaseAdapter {
    fn source_id(&self) -> &str {
        &self.source_id
    }

    fn canonicalize(
        &self,
        raw: &[u8],
        context: &MeasurementContext,
    ) -> Result<Observation, ObserveError> {
        let phase = semantic_phase(raw);
        let payload = raw.to_vec();
        let digest = content_address_raw(&payload);

        // Content-addressed vertex: each unique chunk becomes its own graph node.
        // Two identical chunks (even across sessions) map to the same vertex,
        // enabling genuine cross-session pattern recognition in PatternMemory.
        let chunk_vid = fnv1a_u64(raw);
        let chunk_source = format!("{}-{:016x}", self.source_id, chunk_vid);

        Ok(Observation {
            timestamp: 0.0,
            source_id: chunk_source,
            provenance: ProvenanceEnvelope {
                origin: self.source_id.clone(),
                chain: Vec::new(),
                sig: None,
            },
            payload,
            context: context.clone(),
            digest,
            schema_version: "1.0.0".to_string(),
            phase_hint: Some(phase),
        })
    }
}

// ── Chunker ───────────────────────────────────────────────────────────────────

/// Split a text response into sentence/paragraph chunks for PSE ingestion.
/// Returns each chunk as raw UTF-8 bytes.
pub fn chunk_response(text: &str) -> Vec<Vec<u8>> {
    let mut chunks: Vec<Vec<u8>> = Vec::new();

    for paragraph in text.split('\n') {
        let para = paragraph.trim();
        if para.is_empty() {
            continue;
        }

        let mut start = 0;
        let chars: Vec<char> = para.chars().collect();
        for (i, &ch) in chars.iter().enumerate() {
            if matches!(ch, '.' | '!' | '?') {
                let end = i + 1;
                let sentence: String = chars[start..end].iter().collect();
                let sentence = sentence.trim().to_string();
                if sentence.len() >= 8 {
                    chunks.push(sentence.into_bytes());
                }
                start = end;
            }
        }

        let tail: String = chars[start..].iter().collect();
        let tail = tail.trim().to_string();
        if tail.len() >= 8 {
            chunks.push(tail.into_bytes());
        }
    }

    if chunks.len() < 4 {
        chunks = text
            .split_whitespace()
            .collect::<Vec<_>>()
            .chunks(8)
            .map(|w| w.join(" ").into_bytes())
            .collect();
    }

    chunks
}
