//! Context block generation and specialist activation for nxalien.
//!
//! Produces the [NXALIEN-CONTEXT] injection block, AGENTS.md, CLAUDE.md,
//! and .rules from a compiled NxAlienManifest.

use pse_nxalien_types::{NxAlienManifest, RuleAtom, Severity};

/// Projects a manifest into agent-readable context artefacts.
pub struct ContextProjector {
    /// Maximum characters for the [NXALIEN-CONTEXT] block.
    pub max_chars: usize,
}

impl Default for ContextProjector {
    fn default() -> Self {
        Self { max_chars: 8000 }
    }
}

impl ContextProjector {
    pub fn new(max_chars: usize) -> Self {
        Self { max_chars }
    }

    /// Generate the [NXALIEN-CONTEXT] block for LLM system prompt injection.
    ///
    /// Blocking rules are always emitted first. If the total would exceed
    /// `max_chars`, Required rules are truncated before Advisory rules.
    pub fn render_context_block(&self, manifest: &NxAlienManifest) -> String {
        let mut out = String::new();

        out.push_str(&format!(
            "[NXALIEN-CONTEXT version=\"{}\" replay=\"sha256:{}\"]\n",
            manifest.schema_version, manifest.replay_hash
        ));
        out.push_str(&format!(
            "project: {}\nmode: deterministic-agent-context\nbridge_policy: candidate-only\n\n",
            manifest.metadata.name
        ));

        // Principles (Advisory rules).
        let advisory: Vec<&RuleAtom> = manifest
            .rules
            .iter()
            .filter(|r| r.severity == Severity::Advisory)
            .collect();
        if !advisory.is_empty() {
            out.push_str("[PRINCIPLES]\n");
            for r in &advisory {
                out.push_str(&format!("- {}\n", r.prescription));
            }
            out.push('\n');
        }

        // Open unknowns.
        if !manifest.unknowns.is_empty() {
            out.push_str("[UNKNOWN_SLOTS]\n");
            for u in &manifest.unknowns {
                out.push_str(&format!(
                    "- name:{} status:{:?} confidence:{:.2}\n",
                    u.name, u.status, u.confidence
                ));
            }
            out.push('\n');
        }

        // Blocking rules.
        let blocking: Vec<&RuleAtom> = manifest
            .rules
            .iter()
            .filter(|r| r.severity == Severity::Blocking)
            .collect();
        if !blocking.is_empty() {
            out.push_str("[RULES blocking]\n");
            for r in &blocking {
                out.push_str(&format!("- [{}] {}\n", r.id, r.prescription));
            }
            out.push('\n');
        }

        // Required rules.
        let required: Vec<&RuleAtom> = manifest
            .rules
            .iter()
            .filter(|r| r.severity == Severity::Required)
            .collect();
        if !required.is_empty() {
            out.push_str("[RULES required]\n");
            for r in &required {
                out.push_str(&format!("- [{}] {}\n", r.id, r.prescription));
            }
            out.push('\n');
        }

        // Agenda hints from tool commands.
        let meta = &manifest.metadata;
        let hints: Vec<String> = [
            &meta.test_command,
            &meta.fmt_command,
            &meta.lint_command,
            &meta.build_command,
        ]
        .iter()
        .filter_map(|c| c.as_deref().map(|s| format!("- run `{s}`")))
        .collect();
        if !hints.is_empty() {
            out.push_str("[AGENDA_HINTS]\n");
            for h in hints {
                out.push_str(&h);
                out.push('\n');
            }
            out.push('\n');
        }

        out.push_str("[/NXALIEN-CONTEXT]\n");

        // Truncate at max_chars if needed (preserving opening tag + blocking rules).
        if out.len() > self.max_chars {
            let mut truncated = out[..self.max_chars].to_string();
            truncated.push_str("\n... (truncated)\n[/NXALIEN-CONTEXT]\n");
            truncated
        } else {
            out
        }
    }

    /// Generate AGENTS.md markdown from the manifest.
    pub fn render_agents_md(&self, manifest: &NxAlienManifest) -> String {
        let mut out = String::new();
        out.push_str("# Agent Instructions\n\n");
        out.push_str(&format!(
            "> Generated by nxalien {} — replay `sha256:{}`\n\n",
            manifest.schema_version, manifest.replay_hash
        ));
        out.push_str("## Project\n\n");
        out.push_str(&format!(
            "- **Name**: {}\n- **Language**: {}\n- **Package manager**: {}\n\n",
            manifest.metadata.name, manifest.metadata.language, manifest.metadata.package_manager
        ));
        out.push_str("## Rules\n\n");
        for rule in &manifest.rules {
            let tag = match rule.severity {
                Severity::Blocking => "🚫 BLOCKING",
                Severity::Required => "⚠️ REQUIRED",
                Severity::Advisory => "💡 ADVISORY",
            };
            out.push_str(&format!(
                "### `{}` — {tag}\n\n{}\n\n",
                rule.id, rule.prescription
            ));
        }
        if !manifest.unknowns.is_empty() {
            out.push_str("## Open Unknowns\n\n");
            for u in &manifest.unknowns {
                out.push_str(&format!(
                    "- **{}** (`{:?}`, confidence {:.0}%)\n",
                    u.name,
                    u.status,
                    u.confidence * 100.0
                ));
            }
        }
        out
    }

    /// Generate CLAUDE.md markdown from the manifest.
    pub fn render_claude_md(&self, manifest: &NxAlienManifest) -> String {
        let mut out = String::new();
        out.push_str("# Claude Instructions\n\n");
        out.push_str(&format!(
            "Replay hash: `sha256:{}`\n\n",
            manifest.replay_hash
        ));

        // Commands section.
        let meta = &manifest.metadata;
        out.push_str("## Commands\n\n");
        for (label, cmd) in [
            ("Test", &meta.test_command),
            ("Build", &meta.build_command),
            ("Format", &meta.fmt_command),
            ("Lint", &meta.lint_command),
        ] {
            if let Some(c) = cmd {
                out.push_str(&format!("- **{label}**: `{c}`\n"));
            }
        }
        out.push('\n');

        out.push_str("## Critical Rules\n\n");
        for rule in manifest
            .rules
            .iter()
            .filter(|r| r.severity != Severity::Advisory)
        {
            out.push_str(&format!(
                "- **[{}]** ({}): {}\n",
                rule.id,
                format!("{:?}", rule.severity).to_uppercase(),
                rule.prescription
            ));
        }
        out.push('\n');
        out
    }

    /// Generate .rules plain-text from the manifest.
    pub fn render_rules_file(&self, manifest: &NxAlienManifest) -> String {
        let mut out = String::new();
        out.push_str(&format!(
            "# nxalien rules — {}\n# replay sha256:{}\n\n",
            manifest.metadata.name, manifest.replay_hash
        ));
        for rule in &manifest.rules {
            out.push_str(&format!(
                "[{:?}] {}: {}\n",
                rule.severity, rule.id, rule.prescription
            ));
        }
        out
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use pse_nxalien_types::{
        GateOutcome, NxAlienGateReport, NxAlienManifest, NxAlienRunDescriptor, ProjectMetadata,
        UnknownSlot, UnknownStatus,
    };

    fn test_manifest() -> NxAlienManifest {
        NxAlienManifest {
            schema_version: "1.0".to_string(),
            descriptor: NxAlienRunDescriptor::default(),
            metadata: ProjectMetadata {
                name: "my-project".to_string(),
                language: "rust".to_string(),
                package_manager: "cargo".to_string(),
                test_command: Some("cargo test".to_string()),
                ..Default::default()
            },
            rules: vec![RuleAtom {
                id: "rust-test".to_string(),
                scope: pse_nxalien_types::ScopeRef::default(),
                trigger: vec![],
                prescription: "Run cargo test".to_string(),
                severity: Severity::Blocking,
                evidence: vec![],
                gate: None,
                decay: None,
                hash: "abc123".to_string(),
            }],
            unknowns: vec![UnknownSlot {
                name: "open-question".to_string(),
                domain: vec![],
                status: UnknownStatus::Unknown,
                candidates: vec![],
                evidence: vec![],
                resolution: None,
                confidence: 0.0,
                expires: None,
            }],
            cube_node_count: 5,
            cube_edge_count: 4,
            gate_report: NxAlienGateReport {
                outcome: GateOutcome::Accept,
                ..Default::default()
            },
            manifest_hash: "deadbeef".to_string(),
            replay_hash: "cafebabe".to_string(),
        }
    }

    #[test]
    fn context_block_contains_markers() {
        let projector = ContextProjector::default();
        let block = projector.render_context_block(&test_manifest());
        assert!(block.contains("[NXALIEN-CONTEXT"), "missing opening tag");
        assert!(block.contains("[/NXALIEN-CONTEXT]"), "missing closing tag");
        assert!(block.contains("cafebabe"), "missing replay hash");
    }

    #[test]
    fn agents_md_has_headers() {
        let projector = ContextProjector::default();
        let md = projector.render_agents_md(&test_manifest());
        assert!(md.contains("# Agent Instructions"));
        assert!(md.contains("rust-test"));
    }

    #[test]
    fn rules_file_has_all_rules() {
        let projector = ContextProjector::default();
        let rules = projector.render_rules_file(&test_manifest());
        assert!(rules.contains("rust-test"));
        assert!(rules.contains("Blocking"));
    }
}
